# -*- coding: utf-8 -*-
"""PRACTICAL 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWgofvTlO-4tfzJqHii8QNRLbYVa_wSk

##**PRACTICAL 9**
"""

# Prim's Algorithm without user input

INF = 999999

# Graph represented as an adjacency matrix
graph = [
    [0, 2, INF, 6, INF],
    [2, 0, 3, 8, 5],
    [INF, 3, 0, INF, 7],
    [6, 8, INF, 0, 9],
    [INF, 5, 7, 9, 0]
]

n = len(graph)

# Keep track of vertices included in MST
selected = [False] * n

# Start from vertex 0
selected[0] = True

print("Edges in Minimum Spanning Tree:")

total_cost = 0

for _ in range(n - 1):
    minimum = INF
    x = 0
    y = 0

    # Find the minimum edge connecting selected and unselected vertices
    for i in range(n):
        if selected[i]:
            for j in range(n):
                if not selected[j] and graph[i][j] < minimum:
                    minimum = graph[i][j]
                    x = i
                    y = j

    print(f"{x} - {y} : {graph[x][y]}")

    total_cost += graph[x][y]
    selected[y] = True

print("Total cost of MST:", total_cost)