# -*- coding: utf-8 -*-
"""PRACTICAL 5 DAA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO-Uur_EoViOh_drpRekJzhhZDPMFbPc

##**PRACTICAL 5**
"""

# 0/1 Knapsack Problem using Dynamic Programming

# Given weights and values
weights = [5, 3, 1, 9]
values = [8, 9, 11, 4]

# Maximum capacity of knapsack
capacity = 9

n = len(weights)

# Create DP table
dp = [[0 for _ in range(capacity + 1)] for _ in range(n + 1)]

# Dynamic Programming
for i in range(1, n + 1):
    for w in range(1, capacity + 1):

        if weights[i - 1] <= w:
            dp[i][w] = max(
                values[i - 1] + dp[i - 1][w - weights[i - 1]],
                dp[i - 1][w]
            )
        else:
            dp[i][w] = dp[i - 1][w]

# Display input
print("Weights:", weights)
print("Values :", values)
print("Capacity:", capacity)

# Display result
print("\nMaximum Profit:", dp[n][capacity])